switch from pip to pip3; virtualenv -> python3 venv
farm-ng/tractor pull request #158
Opened 2020-11-25 18:15 UTC by collinbrake

2020-11-25 22:52 UTC, collinbrake commented
@isherman Should I update the dev guide by replacing `git clone git@github.com:USERNAME/tractor ~/tractor` with `git clone -r git@github.com:USERNAME/tractor ~/tractor`, using recursive clone to snag the submodules?

2020-11-25 23:20 UTC, isherman commented
> @isherman Should I update the dev guide by replacing `git clone git@github.com:USERNAME/tractor ~/tractor` with `git clone -r git@github.com:USERNAME/tractor ~/tractor`, using recursive clone to snag the submodules?

Yes, for sure, thank you. 

It's a nit, but let's use `--recursive` instead of `-r` -- using the full flag name in documentation / examples / bash scripts helps new developers understand what's going on.

2020-11-25 23:23 UTC, isherman approved these changes
Approving, but let's wait for CI to go green before merging (just triggered a re-start of CI, since it looked like the failure might have been an ephemeral issue an HTTP endpoint).

2020-11-26 01:08 UTC, collinbrake commented
@isherman We may want to wait on this - the build was successful, but it doesn't look like the executables from the cpp code exist in the build directory yet, and the test for python executables doesn't work yet.

2020-12-04 19:17 UTC, isherman commented on dev.Dockerfile
> +FROM ubuntu:18.04
Can you move this file into `docker/`

2020-12-04 19:17 UTC, isherman commented on bootstrap-venv.sh
> +pip3 install wheel
Looks like this duplicates the above lines

2020-12-04 19:18 UTC, isherman requested changes
added a couple cleanup requests

2020-12-04 19:31 UTC, collinbrake commented
@isherman 

1. Should I squash any of these commits before the merge? It looks like some of your commits are mixed in - not sure how that happened, since I pulled them from this repository.
1. To update the dev wiki, do I clone that separately and edit or should it be included in this PR?

2020-12-04 19:31 UTC, collinbrake commented
@isherman OK, will look into the cleanups.

2020-12-04 21:58 UTC, isherman approved these changes

2020-12-04 21:58 UTC, merged